#!/usr/bin/env bash

set -eo pipefail

NATIVE_IMAGE=`which native-image` || true

if [ -z "$NATIVE_IMAGE" ]; then
  if [ -z "$GRAALVM_HOME" ]; then
      echo "Please set GRAALVM_HOME"
      exit 1
  fi

  NATIVE_IMAGE="$GRAALVM_HOME/bin/native-image"

  if [ ! -x "$NATIVE_IMAGE" ]; then
    "$GRAALVM_HOME/bin/gu" install native-image || true
  fi
fi

jar=${1:-target/rebel-readline-0.1.5-SNAPSHOT-standalone.jar}

"$NATIVE_IMAGE" \
  -jar "$jar" \
  -H:Name=rebel-readline \
  -H:+ReportExceptionStackTraces \
  -J-Dclojure.spec.skip-macros=true \
  -J-Dclojure.compiler.direct-linking=true \
  -J-Dorg.jline.terminal.disableDeprecatedProviderWarning=true \
  -H:IncludeResources='org/jline/utils/.*' \
  --initialize-at-build-time \
  -H:Log=registerResource: \
  -H:EnableURLProtocols=http,https \
  --enable-all-security-services \
  --verbose \
  --no-fallback \
  --no-server \
  --report-unsupported-elements-at-runtime \
  -H:+PrintClassInitialization \
  -J-Xmx6g
